## ALL AUTHORS 
GET http://localhost:8000/api/authors/

### SINGLE AUTHORS
GET http://localhost:8000/api/authors/3

### ALL BOOKS
GET http://localhost:8000/api/books/
 
 ### First POST request
POST http://localhost:8000/api/authors/ HTTP/1.1
Content-Type: application/json

{
    "name": "Mike Forscutt",
    "title": "Legend",
    "company": "Mike",
    "email": "test@mike.com"
}